<div class="container-fluid">
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-10">
                <div id="container">
                    <h1 id="pageTitle">404 - Car does not exist</h1>
                    <br/>
                    <br/>
                    <p>The car you are looking for is not recognized here. Please go back, go to the <a href='<?php
                                        echo $this->url(array(
                                            'controller' => 'car-page',
                                                'action' => 'index'
                                         ), null, true);
                                        ?>' style="color:#FF0000;">car listing page</a> or <a href="<?php
                                        echo $this->url(array(
                                            'controller' => 'index',
                                                'action' => 'index'
                                         ), null, true);
                                    ?>" style="color:#FF0000;">return to main page</a></p>
                    <br/>
                    <br/>
                    <br/>
                    <br/>
                    <br/>
                    <br/>
                    <br/>
                    <br/>
                    <br/>
                    <br/>
                    <br/>
                    <br/>
                    <br/>
                    <br/>
                    <br/>
                    <br/>
                </div>
            </div>
            <div class="col-sm-1"></div>
        </div>
    </div>