<div class="container-fluid">
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-10">
                <div id="container">
                <h1 id="pageTitle">Cars For Sale</h1>
                    <div class="container-fluid">
                        <?php foreach ($this->cars as $car) : ?>
                        <div class="row" style="border:1px solid;">
                            <div class="col-sm-4" id="indexTableCell">
                                <?php if ($this->escape($car->carPicture) == null) : ?>
                                    <img id="indexCarPhoto" src='<?php echo $this->baseUrl()?>/images/pictureNotUploaded.bmp' class="button" alt='No Picture' style="margin:auto; width:100%;">
                                <?php else: ?>
                                    <img id="indexCarPhoto" src='<?php echo $this->baseUrl()?>/images/<?php echo ($this->escape($car->carPicture)); ?>.jpg' class="button" alt='No Picture' style="margin:auto; width:100%;">
                                <?php endif; ?>
                            </div>
                            <div class="col-sm-5">
                                <h2><?php echo htmlentities($this->escape($car->make)); ?></h2>  
                                <h4><?php echo htmlentities($this->escape($car->model)); ?></h4>
                                <br/>
                                <table>
                                    <tr>
                                        <td style="width:130px;"><img id="indexLogos" src="<?php echo $this->baseUrl()?>/images/mileageLogo.bmp" alt="no picture"/></td>
                                        <td style="width:40%;">&nbsp;<?php echo htmlentities($this->escape($car->mileage)); ?> </td>
                                        <td style="width:5%;"><img id="indexLogos" src="<?php echo $this->baseUrl()?>/images/transmissionLogo.bmp" alt="no picture"/></td>
                                        <td style="width:auto;">&nbsp;<?php echo htmlentities($this->escape($car->transmission)); ?></td>
                                    </tr>
                                    <tr><td><br/></td></tr>
                                    <tr>
                                        <td style="width:5%;"><img id="indexLogos" src="<?php echo $this->baseUrl()?>/images/colourLogo.bmp" alt="no picture"/></td>
                                        <td style="width:40%;">&nbsp;<?php echo htmlentities($this->escape($car->colour)); ?> </td>
                                        <td style="width:5%;"><img id="indexLogos" src="<?php echo $this->baseUrl()?>/images/bodyTypeLogo.bmp" alt="no picture"/></td>
                                        <td style="width:auto;">&nbsp;<?php echo htmlentities($this->escape($car->bodyType)); ?></td>
                                    </tr>
                                    <tr><td><br/></td></tr>
                                    <tr>
                                        <td style="width:5%;"><img id="indexLogos" src="<?php echo $this->baseUrl()?>/images/fuelTypeLogo.bmp" alt="no picture"/></td>
                                        <td style="width:40%;">&nbsp;<?php echo htmlentities($this->escape($car->fuelType)); ?></td>
                                    </tr>
                                    <tr><td><br/></td></tr>
                                </table>
                            </div>
                            <div class="col-sm-3" style="text-align:center;">
                                <h2 id="priceTag" style="color:#FF0000; text-align:center;"><strong><u>&pound;<?php echo htmlentities($this->escape($car->price)); ?></u></strong></h2>
                                <br/>
                                <form id="postForm" action="<?php echo $this->url(array('action' => 'view', 'controller' => 'car-page', 'id' => $car->id)); ?>" method="post">
                                    <input id="indexButton" type="submit" name="submit" value="VIEW FULL DETAILS" style="box-sizing:border-box; color:white; background-color:#FF0000; font-weight:bold; -moz-border-radius:8px; -webkit-border-radius: 8px; border-radius:8px; border-color:#FFA500;">
                                </form>
                                <br/>
                            </div>
                        </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-1"></div>
    </div>
    <br/>
    <br/>
    <br/>
