<div class="container-fluid">
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-10">
                <div id="container">
                <h1 id="pageTitle">Welcome to Real Autos!</h1>
                <br/>
                <br/>
                <p>Description.......This is a simple demonstration of my learning of the Zend framework.</p>
                <br/>
                <p>Please note that this is not a real company, nor am I developing it for a client.</p>
                <br/>
                <h2 style="text-align:center;"><strong><u><a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'car-page')); ?>" style="color:#FF0000;">Available Cars For Sale</a></u></strong></h2>
                <br/>
                    
                </div>
            </div>
        </div>
        <div class="col-sm-1"></div>
    </div>
    <br/>
    <br/>
    <br/>
