<?php
//Append HTTP type
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
//Seperator for between the prepended page title and the main website title
$this->headTitle()->setSeparator(' - ');
//The headTitle - The main title of this website, and which the titles of each page is prepended before it
$this->headTitle('Real Autos');
?>
<html>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php
        echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css');
        echo $this->headScript();
        echo $this->headStyle();
        ?>
        <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
        <!-- Link for the latest compiled and minified Bootstrap stylesheet  -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <!-- Script for the latest compiled JavaScript (Bootstrap) -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <style>
            #navButton {
                color:#FFF;
                font-weight:bold;
                font-size:18px;
                height:55px;
                box-sizing: border-box;
                margin-top:5px;
                margin-bottom:5px;
            }

            #navButton:hover {
                text-decoration: underline white;
                color:#FFFFFF;
            }

            #navButton:active {
                color:#FF0000;
                background-color: #FFFFFF;
            }

            #footer {
                background-color: #FF0000;
                font-size:1.2em;
                color:#FFF;
            }

            #col1 {
                list-style-type:none; 
                margin-left:15%;
            }

            #col2 {
                list-style-type:none;
                margin-right:15%;
                word-wrap:break-word;
            }

            /* Desktop & Mobile Screens Set to 1024 x 768 or Below  */
            @media screen and (max-width: 1024px) {
                #navButton {
                    font-size:15px;
                }
            }

            /* Desktop & Mobile Screens Set to 640 x 768 or Below  */
            @media screen and (max-width: 768px) {   
                #navButton {
                    margin-left:10%;
                    margin-right:10%;
                }

                #col1 {
                    list-style-type:none; 
                    margin-left:0px;
                    margin-right:15%;
                }

                #col2 {
                    list-style-type:none; 
                }

                #footer {
                    font-size:1.2em;
                }
            }

            /* Desktop & Mobile Screens Set to 640 pixels or Below  */
            @media screen and (max-width: 640px) {
                #footer {
                    font-size:1.2em;
                }
            }

            /* Desktop & Mobile Screens Set to 480 pixels or Below  */
            @media screen and (max-width: 480px) {
                #footer {
                    font-size:1.2em;
                }
            }

            /* Desktop & Mobile Screens Set to 320 pixels or below  */
            @media screen and (max-width: 320px) {
                #footer {
                    font-size:1.2em;
                }
            }
        </style>
    </head>
    <body style="background-color:#FFFFFF;">
        <div>
            <header id="title" class="grid_16">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-10">
                            <a href="<?php
                            echo $this->url(array(
                                'controller' => 'index',
                                'action' => 'index'
                            ));
                            ?>" style="text-decoration-color:#FF0000;"><h1 style="font-size:60px; color:#FF0000;"><strong>REAL AUTOS</strong></h1></a>
                        </div>
                        <div class="col-sm-1"></div>
                    </div>
                </div>
            </header>
            <nav>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-10">
                            <div class="menu">
                                <div class="navbar navbar-default navbar-static-top" role="navigation" style="background-color:#FF0000; text-align:center;">
                                    <div class='container-fluid'>
                                        <div class="navbar-header">
                                            <button type="button" class="pull-left navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" style="background-color:#FFF; margin-left:2%;">
                                                <span class="icon-bar"></span>
                                                <span class="icon-bar"></span>
                                                <span class="icon-bar"></span>
                                            </button>
                                        </div>
                                        <div class="collapse navbar-collapse">
                                            <ul class="nav navbar-nav">
                                                <li><a href="<?php
                                                    echo $this->url(array(
                                                        'controller' => 'index',
                                                        'action' => 'index'
                                                    ), null, true);
                                                    ?>" id="navButton">HOME</a></li>
                                                <li style="color:white"><a href="<?php
                                                    echo $this->url(array(
                                                        'controller' => 'car-page',
                                                        'action' => 'index'
                                                    ), null, true);
                                                    ?>" id="navButton">CAR LIST</a></li>  
                                                <li><a href="<?php
                                                    echo $this->url(array(
                                                        'controller' => 'we-buy-cars',
                                                        'action' => 'index'
                                                    ), null, true);
                                                    ?>" id="navButton">WE BUY CARS</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-1"></div>
                    </div>
                </div>
            </nav>
            <section id="body" style="background-color:#FFFFFF;">
                <br/>
                <p><?php echo $this->layout()->content; ?></p>
            </section>
            <footer>
                <div id="footer">
                    <br/>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-1"></div>
                            <div class="col-sm-4">
                                <table>
                                    <tr>
                                        <td>
                                            <ul id="col1">
                                                <li style="color:white"><h4><u>Site Map</u></h4></li>
                                                <li><p></p></li>
                                                <li style="color:white">+<a href="<?php
                                                    echo $this->url(array(
                                                        'controller' => 'index',
                                                        'action' => 'index'
                                                    ), null, true);
                                                    ?>" style="color:white">Home</a></li>
                                                <li><p></p></li>
                                                <li style="color:white">+<a href="<?php
                                                    echo $this->url(array(
                                                        'controller' => 'car-page',
                                                        'action' => 'index'
                                                    ), null, true);
                                                    ?>" style="color:white">Car List</a></li>
                                                <li><p></p></li>
                                                <li style="color:white">+<a href="<?php
                                                    echo $this->url(array(
                                                        'controller' => 'we-buy-cars',
                                                        'action' => 'index'
                                                    ), null, true);
                                                    ?>" style="color:white">We Buy Cars</a></li>
                                            </ul>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-sm-7"></div>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </body>
</html>